<a href="https://colab.research.google.com/github/Wishmi-Sasika/MLOM-Labs/blob/main/MLOM_Lab_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive


In [ ]:
filename = '/content/drive/MyDrive/Colab Notebooks/Data/data.txt'
raw_text = open (filename, 'r', encoding = 'utf-8').read()
raw_text = raw_text.lower()

In [ ]:
# Create mapping of unique chars to integers
chars = sorted (list (set (raw_text)))
print (chars)
char_to_int = dict ((c, i) for i, c in enumerate (chars))

['\n', ' ', '!', '"', '#', '$', '%', "'", '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', '@', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [ ]:
print (char_to_int)

{'\n': 0, ' ': 1, '!': 2, '"': 3, '#': 4, '$': 5, '%': 6, "'": 7, '(': 8, ')': 9, '*': 10, ',': 11, '-': 12, '.': 13, '/': 14, '0': 15, '1': 16, '2': 17, '3': 18, '4': 19, '5': 20, '6': 21, '7': 22, '8': 23, '9': 24, ':': 25, ';': 26, '?': 27, '@': 28, '[': 29, ']': 30, '_': 31, 'a': 32, 'b': 33, 'c': 34, 'd': 35, 'e': 36, 'f': 37, 'g': 38, 'h': 39, 'i': 40, 'j': 41, 'k': 42, 'l': 43, 'm': 44, 'n': 45, 'o': 46, 'p': 47, 'q': 48, 'r': 49, 's': 50, 't': 51, 'u': 52, 'v': 53, 'w': 54, 'x': 55, 'y': 56, 'z': 57}


In [ ]:
int_to_char = {i: char for i, char in enumerate (chars)}

In [ ]:
print (int_to_char)

{0: '\n', 1: ' ', 2: '!', 3: '"', 4: '#', 5: '$', 6: '%', 7: "'", 8: '(', 9: ')', 10: '*', 11: ',', 12: '-', 13: '.', 14: '/', 15: '0', 16: '1', 17: '2', 18: '3', 19: '4', 20: '5', 21: '6', 22: '7', 23: '8', 24: '9', 25: ':', 26: ';', 27: '?', 28: '@', 29: '[', 30: ']', 31: '_', 32: 'a', 33: 'b', 34: 'c', 35: 'd', 36: 'e', 37: 'f', 38: 'g', 39: 'h', 40: 'i', 41: 'j', 42: 'k', 43: 'l', 44: 'm', 45: 'n', 46: 'o', 47: 'p', 48: 'q', 49: 'r', 50: 's', 51: 't', 52: 'u', 53: 'v', 54: 'w', 55: 'x', 56: 'y', 57: 'z'}


In [ ]:
n_chars = len (raw_text)
n_vocab = len (chars)
print ("Total characters : ", n_chars)
print ("Total vocab (unique characters) : ", n_vocab)

Total characters :  163780
Total vocab (unique characters) :  58


In [ ]:
# Prepare the dataset of input to output pairs encoded as integers
seq_length = 15   # can be changed
                  # including spaces also.
dataX = []
dataY = []

for i in range (0, n_chars - seq_length, 1):
  seq_in = raw_text [i: i + seq_length]
  seq_out = raw_text [i + seq_length]
  dataX.append ([char_to_int[char] for char in seq_in])
  dataY.append ([char_to_int[seq_out]])

n_patterns = len (dataY)
print ("Total patterns : ", n_patterns)

Total patterns :  163765


In [ ]:
print (dataY)

[[49], [38], [7], [50], [1], [32], [43], [40], [34], [36], [7], [50], [1], [32], [35], [53], [36], [45], [51], [52], [49], [36], [50], [1], [40], [45], [1], [54], [46], [45], [35], [36], [49], [43], [32], [45], [35], [11], [1], [33], [56], [1], [43], [36], [54], [40], [50], [1], [34], [32], [49], [49], [46], [43], [43], [0], [0], [51], [39], [40], [50], [1], [36], [33], [46], [46], [42], [1], [40], [50], [1], [37], [46], [49], [1], [51], [39], [36], [1], [52], [50], [36], [1], [46], [37], [1], [32], [45], [56], [46], [45], [36], [1], [32], [45], [56], [54], [39], [36], [49], [36], [1], [32], [51], [1], [45], [46], [1], [34], [46], [50], [51], [1], [32], [45], [35], [1], [54], [40], [51], [39], [0], [32], [43], [44], [46], [50], [51], [1], [45], [46], [1], [49], [36], [50], [51], [49], [40], [34], [51], [40], [46], [45], [50], [1], [54], [39], [32], [51], [50], [46], [36], [53], [36], [49], [13], [1], [1], [56], [46], [52], [1], [44], [32], [56], [1], [34], [46], [47], [56], [1], [40], 

In [ ]:
print (dataX)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
import numpy

# Preprocessing

# Reshape X to be [sample, time steps, features]
X = numpy.reshape (dataX, (n_patterns, seq_length, 1))

# Normalize - rescaling the integer values
X = X / float(n_vocab)
print (X)

[[[0.81034483]
  [0.84482759]
  [0.79310345]
  ...
  [0.77586207]
  [0.56896552]
  [0.62068966]]

 [[0.84482759]
  [0.79310345]
  [0.70689655]
  ...
  [0.56896552]
  [0.62068966]
  [0.84482759]]

 [[0.79310345]
  [0.70689655]
  [0.62068966]
  ...
  [0.62068966]
  [0.84482759]
  [0.65517241]]

 ...

 [[0.55172414]
  [0.56896552]
  [0.79310345]
  ...
  [0.79310345]
  [0.79310345]
  [0.72413793]]

 [[0.56896552]
  [0.79310345]
  [0.89655172]
  ...
  [0.79310345]
  [0.72413793]
  [0.86206897]]

 [[0.79310345]
  [0.89655172]
  [0.87931034]
  ...
  [0.72413793]
  [0.86206897]
  [0.22413793]]]


In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.utils import to_categorical

In [ ]:
# One hot encode the output variable
y = to_categorical(dataY)
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import ModelCheckpoint

In [ ]:
# Define the LSTM model
model = Sequential()
model.add (LSTM (256, input_shape = (X.shape[1], X.shape[2])))  # it can have 1 or more training samples
model.add (Dropout (0.2))
model.add (Dense (y.shape[1], activation = 'softmax'))
model.compile (loss = 'categorical_crossentropy', optimizer = 'adam')

# Define the checkpoint
filepath = "weights-improvement-{epoch:02d}-{loss:.4f}.hdfs"
checkpoint = ModelCheckpoint (filepath, monitor = 'loss', verbose = 1, save_best_only = True, mode = 'min')
callbacks_list = [checkpoint]

In [ ]:
# Change the hyperparameter values and train model
epochs = 10
batch_size = 128

model.fit (X, y, epochs = epochs, batch_size = batch_size, callbacks = callbacks_list)

Epoch 1/10
1280/1280 [==============================] - ETA: 0s - loss: 2.9874
Epoch 1: loss improved from inf to 2.98744, saving model to weights-improvement-01-2.9874.hdfs
1280/1280 [==============================] - 151s 115ms/step - loss: 2.9874
Epoch 2/10
1280/1280 [==============================] - ETA: 0s - loss: 2.7931
Epoch 2: loss improved from 2.98744 to 2.79312, saving model to weights-improvement-02-2.7931.hdfs
1280/1280 [==============================] - 147s 115ms/step - loss: 2.7931
Epoch 3/10
1280/1280 [==============================] - ETA: 0s - loss: 2.7166
Epoch 3: loss improved from 2.79312 to 2.71660, saving model to weights-improvement-03-2.7166.hdfs
1280/1280 [==============================] - 151s 118ms/step - loss: 2.7166
Epoch 4/10
1280/1280 [==============================] - ETA: 0s - loss: 2.6634
Epoch 4: loss improved from 2.71660 to 2.66335, saving model to weights-improvement-04-2.6634.hdfs
1280/1280 [==============================] - 148s 115ms/step - l

In [ ]:
#load the network weights
filename="weights-improvement-10-2.4088.hdfs"
model.load_weights(filename)
model.compile(loss='categorical_crossentropy',optimizer='adam')

In [ ]:
int_to_char={i:char for i, char in enumerate(chars)}
print(int_to_char)

{0: '\n', 1: ' ', 2: '!', 3: '"', 4: '#', 5: '$', 6: '%', 7: "'", 8: '(', 9: ')', 10: '*', 11: ',', 12: '-', 13: '.', 14: '/', 15: '0', 16: '1', 17: '2', 18: '3', 19: '4', 20: '5', 21: '6', 22: '7', 23: '8', 24: '9', 25: ':', 26: ';', 27: '?', 28: '@', 29: '[', 30: ']', 31: '_', 32: 'a', 33: 'b', 34: 'c', 35: 'd', 36: 'e', 37: 'f', 38: 'g', 39: 'h', 40: 'i', 41: 'j', 42: 'k', 43: 'l', 44: 'm', 45: 'n', 46: 'o', 47: 'p', 48: 'q', 49: 'r', 50: 's', 51: 't', 52: 'u', 53: 'v', 54: 'w', 55: 'x', 56: 'y', 57: 'z'}


In [ ]:
#generate a random seed
print(len(dataX))
start=numpy.random.randint(0,len(dataX)-1)
print(start)
pattern=dataX[start] #dataX contain list of patterns
print("Seed:")
print("\"",''.join([int_to_char[value] for value in pattern]),"\"")

163765
26209
Seed:
"  said alice; no "


In [ ]:
length=10
final=[]
for i in range(length):
  x=numpy.reshape(pattern,(1,len(pattern),1))
  x=x/float(n_vocab)
  print(x)
  prediction=model.predict(x,verbose=0)
  index=numpy.argmax(prediction)
  result=int_to_char[index]
  final.append(result)
  pattern.append(index)
  pattern=pattern[1:len(pattern)]
print(final)

[[[0.01724138]
  [0.86206897]
  [0.55172414]
  [0.68965517]
  [0.60344828]
  [0.01724138]
  [0.55172414]
  [0.74137931]
  [0.68965517]
  [0.5862069 ]
  [0.62068966]
  [0.44827586]
  [0.01724138]
  [0.77586207]
  [0.79310345]]]
[[[0.86206897]
  [0.55172414]
  [0.68965517]
  [0.60344828]
  [0.01724138]
  [0.55172414]
  [0.74137931]
  [0.68965517]
  [0.5862069 ]
  [0.62068966]
  [0.44827586]
  [0.01724138]
  [0.77586207]
  [0.79310345]
  [0.01724138]]]
[[[0.55172414]
  [0.68965517]
  [0.60344828]
  [0.01724138]
  [0.55172414]
  [0.74137931]
  [0.68965517]
  [0.5862069 ]
  [0.62068966]
  [0.44827586]
  [0.01724138]
  [0.77586207]
  [0.79310345]
  [0.01724138]
  [0.87931034]]]
[[[0.68965517]
  [0.60344828]
  [0.01724138]
  [0.55172414]
  [0.74137931]
  [0.68965517]
  [0.5862069 ]
  [0.62068966]
  [0.44827586]
  [0.01724138]
  [0.77586207]
  [0.79310345]
  [0.01724138]
  [0.87931034]
  [0.67241379]]]
[[[0.60344828]
  [0.01724138]
  [0.55172414]
  [0.74137931]
  [0.68965517]
  [0.5862069 ]
  