<a href="https://colab.research.google.com/github/Wishmi-Sasika/MLOM-Labs/blob/main/MLOM_Lab_Exam_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt


In [ ]:
# Importing the data
data = pd.read_csv('https://raw.githubusercontent.com/lakminia/Market_data_IT3071/main/Market_data_set.csv')

In [ ]:
data.head()

QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES   STATUS  QTR_ID  \
0               30      95.70                2  2871.00  Shipped       1   
1               34      81.35                5  2765.90  Shipped       2   
2               41      94.74                2  3884.34  Shipped       3   
3               45      83.26                6  3746.70  Shipped       3   
4               49     100.00               14  5205.27  Shipped       4   

   MONTH_ID  YEAR_ID  PRODUCTLINE  MSRP  Product_SK PRODUCTCODE  Customer_SK  \
0         2     2003  Motorcycles    95           1    S10_1678            1   
1         5     2003  Motorcycles    95           2    S10_1678            2   
2         7     2003  Motorcycles    95           3    S10_1678            3   
3         8     2003  Motorcycles    95           4    S10_1678            4   
4        10     2003  Motorcycles    95           5    S10_1678            5   

  COUNTRY DEALSIZE  
0     USA    Small  
1  France    Small  
2  France   Medium  
3     USA   Medium  
4     USA   Medium

In [ ]:
data.shape

(2823, 15)

In [ ]:
data['DEALSIZE'].replace( {'Small': 0,'Medium': 1, 'Large': 2}, inplace=True)

In [ ]:
data.head()

QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES   STATUS  QTR_ID  \
0               30      95.70                2  2871.00  Shipped       1   
1               34      81.35                5  2765.90  Shipped       2   
2               41      94.74                2  3884.34  Shipped       3   
3               45      83.26                6  3746.70  Shipped       3   
4               49     100.00               14  5205.27  Shipped       4   

   MONTH_ID  YEAR_ID  PRODUCTLINE  MSRP  Product_SK PRODUCTCODE  Customer_SK  \
0         2     2003  Motorcycles    95           1    S10_1678            1   
1         5     2003  Motorcycles    95           2    S10_1678            2   
2         7     2003  Motorcycles    95           3    S10_1678            3   
3         8     2003  Motorcycles    95           4    S10_1678            4   
4        10     2003  Motorcycles    95           5    S10_1678            5   

  COUNTRY  DEALSIZE  
0     USA         0  
1  France         0  
2  France         1  
3     USA         1  
4     USA         1

In [ ]:
for column_name in data:
      print(column_name)
      s = data['DEALSIZE'].unique()
      print(s)

QUANTITYORDERED
[0 1 2]
PRICEEACH
[0 1 2]
ORDERLINENUMBER
[0 1 2]
SALES
[0 1 2]
STATUS
[0 1 2]
QTR_ID
[0 1 2]
MONTH_ID
[0 1 2]
YEAR_ID
[0 1 2]
PRODUCTLINE
[0 1 2]
MSRP
[0 1 2]
Product_SK
[0 1 2]
PRODUCTCODE
[0 1 2]
Customer_SK
[0 1 2]
COUNTRY
[0 1 2]
DEALSIZE
[0 1 2]


In [ ]:
data.isna().sum()

QUANTITYORDERED    0
PRICEEACH          0
ORDERLINENUMBER    0
SALES              0
STATUS             0
QTR_ID             0
MONTH_ID           0
YEAR_ID            0
PRODUCTLINE        0
MSRP               0
Product_SK         0
PRODUCTCODE        0
Customer_SK        0
COUNTRY            0
DEALSIZE           0
dtype: int64

In [ ]:
# Ndata = pd.get_dummies('STATUS','PRODUCTLINE', 'PRODUCTCODE', 'COUNTRY')
ndata = pd.get_dummies(data, columns = ['STATUS','PRODUCTLINE', 'PRODUCTCODE', 'COUNTRY'])

In [ ]:
x = ndata.drop('DEALSIZE', axis = 1)
y = ndata['DEALSIZE']

In [ ]:
x.shape

(2823, 151)

In [ ]:
y.head()

0    0
1    0
2    1
3    1
4    1
Name: DEALSIZE, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=4, shuffle=True)

In [ ]:
# Defining the model
model = tf.keras.Sequential([


    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(16, activation = 'relu'),
    tf.keras.layers.Dense(3, activation = 'softmax')
])

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

# Compiling the model
model.compile(optimizer=optimizer,
              loss=keras.losses.SparseCategoricalCrossentropy(),
              metrics=['accuracy'])

In [ ]:
# fitting the model
history = model.fit(X_train, y_train, epochs=30, batch_size=32, validation_data = (X_test, y_test))

In [ ]:
results = model.evaluate(X_test, y_test, batch_size=32)

In [ ]:
predictions = model.predict(X_test[10:])
predictions

In [ ]:
loss_train = history.history['loss']
loss_val = history.history['val_loss']

In [ ]:
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend()



In [ ]:
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')